version: '2.0'
services:
    iac_basestation:
        image: iacteams/basestation:latest
        build:
          # docker build context
          context: ${IAC_BASESTATION_ROOT}
          dockerfile: ${IAC_BASESTATION_ROOT}/operations/dockerfiles/basestation.Dockerfile
        container_name: iac_basestation
        tty: true
        network_mode: "host"
        privileged: true
        security_opt:
            - seccomp:unconfined
        volumes:
            - ${IAC_BASESTATION_ROOT}/operations:/workspace/operations
            - ${IAC_BASESTATION_ROOT}/build:/workspace/build
            - ${IAC_BASESTATION_ROOT}/install:/workspace/install
            - ${IAC_BASESTATION_ROOT}/src/joystick_vehicle_interface:/workspace/src/joystick_vehicle_interface
            - ${IAC_BASESTATION_ROOT}/src/joystick_vehicle_interface_nodes:/workspace/src/joystick_vehicle_interface_nodes
            - ${IAC_BASESTATION_ROOT}/src/userinput:/workspace/src/userinput
            - ${IAC_BASESTATION_ROOT}/src/bvs_msgs:/workspace/src/bvs_msgs
            - ${IAC_BASESTATION_ROOT}/src/deep_orange_msgs:/workspace/src/deep_orange_msgs
            - ${IAC_BASESTATION_ROOT}/src/nif_msgs:/workspace/src/nif_msgs
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - /dev/input:/dev/input
