version: '2.4'
services:
    nifbasestation_sim:
        runtime: nvidia
        image: nif/basestation:sim
        build:
          # docker build context
          context: ${IAC_BASESTATION_ROOT}
          dockerfile: ${IAC_BASESTATION_ROOT}/operations/dockerfiles/basestation.Dockerfile
        container_name: nifbasestation_sim
        tty: true
        network_mode: "host"
        privileged: true
        security_opt:
            - seccomp:unconfined
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - ${IAC_BASESTATION_ROOT}/operations:/workspace/operations
            - ${IAC_BASESTATION_ROOT}/build:/workspace/build
            - ${IAC_BASESTATION_ROOT}/install:/workspace/install
            - ${IAC_BASESTATION_ROOT}/src/joystick_vehicle_interface:/workspace/src/joystick_vehicle_interface
            - ${IAC_BASESTATION_ROOT}/src/joystick_vehicle_interface_nodes:/workspace/src/joystick_vehicle_interface_nodes
            - ${IAC_BASESTATION_ROOT}/src/userinput:/workspace/src/userinput
            - ${IAC_BASESTATION_ROOT}/src/bvs_msgs:/workspace/src/bvs_msgs
            - ${IAC_BASESTATION_ROOT}/src/deep_orange_msgs:/workspace/src/deep_orange_msgs
            - ${IAC_BASESTATION_ROOT}/src/nif_msgs:/workspace/src/nif_msgs
            - ${IAC_BASESTATION_ROOT}/src/py_pubsub:/workspace/src/py_pubsub
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - /dev/input:/dev/input
            #- ${IAC_BASESTATION_ROOT}/src/zenoh-bridge-dds:/usr/bin/zenoh-bridge-dds
