version: '2.0'
services:
    iac_basestation:
        image: iacteams/basestation
        build:
          # docker build context
          context: ${IAC_BASESTATION_ROOT}
          dockerfile: ${IAC_BASESTATION_ROOT}/operations/dockerfiles/basestation.Dockerfile
        container_name: iac_basestation
        tty: true
        network_mode: "host"
        privileged: true
        security_opt:
            - seccomp:unconfined
        volumes:
            - ${IAC_BASESTATION_ROOT}:/workspace
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - /dev/input:/dev/input
