session_name: iac_basestation_launch
windows:
  - window_name: Joystick Launch
    layout: tiled
    panes:
    - shell_command:
      - echo "Sleeping 5 seconds before launching zenoh"
      - sleep 2
      - /workspace/operations/scripts/bst_fm.sh
    - shell_command:
      - ros2 launch joystick_vehicle_interface_nodes joystick_vehicle_interface_node.launch.py
  - window_name: User Inputs
    layout: tiled
    panes:
    - shell_command:
      - ros2 run userinput ui_raceflag
    - shell_command:
      - ros2 run userinput ui_publisher
    - shell_command:
      - /workspace/operations/scripts/remote_spoof_spawn.sh
    - shell_command:
      - /workspace/operations/scripts/remote_sensors_bagging.sh
  - window_name: Ping and State
    layout: main-horizontal
    options:
      main-pane-height: 20
    panes:
    - shell_command:
      - echo "PING for 10.42.4.200 (ADLINK)"
      - ping 10.42.4.200
    - shell_command:
      - sleep 5
      - ros2 topic echo /telemetry/misc_report_do deep_orange_msgs/msg/MiscReport
    - shell_command:
      - sleep 5
      - ros2 topic echo /telemetry/ct_report deep_orange_msgs/msg/CtReport
    - shell_command:
      - sleep 5
      - ros2 topic echo /telemetry/safety_status bvs_msgs/msg/SafetyStatus
    - shell_command:
      - sleep 5
      - ros2 topic echo /telemetry/pt_report deep_orange_msgs/msg/PtReport
