session_name: nifbasestation_launch
windows:
  - window_name: Joystick Launch
    layout: tiled
    panes:
    - shell_command:
      - echo "Sleeping 5 seconds before launching zenoh"
      - sleep 2
      - /workspace/operations/scripts/bst_fm.sh
    - shell_command:
      - ros2 launch joystick_vehicle_interface_nodes joystick_vehicle_interface_node.launch.py
  - window_name: User Inputs
    layout: tiled
    panes:
    - shell_command:
      # - ros2 run plotjuggler plotjuggler -l src/py_pubsub/assets/base_station_plot_config.xml
    - shell_command:
      # - ros2 run py_pubsub plot2 
    - shell_command:
      - ros2 run userinput ui_raceflag
    - shell_command:
      - ros2 run userinput ui_publisher
  - window_name: Ping and State
    layout: even-horizontal
    options:
      main-pane-height: 7
    panes:
    - shell_command:
      - echo "PING for 10.42.4.200 (ADLINK)"
      - ping 10.42.4.200
    - shell_command:
      - sleep 5
      - ros2 topic echo /nif_telemetry/telemetry nif_msgs/msg/Telemetry
    - shell_command:
      - sleep 5
      - ros2 topic echo /nif_telemetry/system_status nif_msgs/msg/SystemStatus
